//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarWeb.ListCarsServiceReference {
    using System;
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListCarsServiceReference.ListCarsServiceSoap")]
    public interface ListCarsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/readAllInDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable readAllInDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/readAllInDataTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> readAllInDataTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/readAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RentalCarWeb.ListCarsServiceReference.Car[] readAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/readAll", ReplyAction="*")]
        System.Threading.Tasks.Task<RentalCarWeb.ListCarsServiceReference.Car[]> readAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchCars", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RentalCarWeb.ListCarsServiceReference.Car[] searchCars(string plate, string model, string city, System.DateTime presentStartDate, System.DateTime presentEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchCars", ReplyAction="*")]
        System.Threading.Tasks.Task<RentalCarWeb.ListCarsServiceReference.Car[]> searchCarsAsync(string plate, string model, string city, System.DateTime presentStartDate, System.DateTime presentEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateCarPlate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validateCarPlate(string carPlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateCarPlate", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> validateCarPlateAsync(string carPlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateCarModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validateCarModel(string carModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateCarModel", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> validateCarModelAsync(string carModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validateCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateCity", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> validateCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validateDate(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateDate", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> validateDateAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateRentPeriod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validateRentPeriod(string plate, System.DateTime presentStartDate, System.DateTime presentEndDate, string condition, RentalCarWeb.ListCarsServiceReference.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateRentPeriod", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> validateRentPeriodAsync(string plate, System.DateTime presentStartDate, System.DateTime presentEndDate, string condition, RentalCarWeb.ListCarsServiceReference.Reservation reservation);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Car : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int carIDField;
        
        private string plateField;
        
        private string manufacturerField;
        
        private string modelField;
        
        private double priceField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int carID {
            get {
                return this.carIDField;
            }
            set {
                this.carIDField = value;
                this.RaisePropertyChanged("carID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string plate {
            get {
                return this.plateField;
            }
            set {
                this.plateField = value;
                this.RaisePropertyChanged("plate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int carIDField;
        
        private string carPlateField;
        
        private int costumerIDField;
        
        private int reservStatsIDField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string locationField;
        
        private string couponCodeField;

        public Reservation(int carID, string carPlate, int costumerID, int reservStatsID, DateTime startDate, DateTime endDate, string location, string couponCode)
        {
            this.carID = carID;
            this.carPlate = carPlate;
            this.costumerID = costumerID;
            this.reservStatsID = reservStatsID;
            this.startDate = startDate;
            this.endDate = endDate;
            this.location = location;
            this.couponCode = couponCode;
        }

        public Reservation() { }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int carID {
            get {
                return this.carIDField;
            }
            set {
                this.carIDField = value;
                this.RaisePropertyChanged("carID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string carPlate {
            get {
                return this.carPlateField;
            }
            set {
                this.carPlateField = value;
                this.RaisePropertyChanged("carPlate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int costumerID {
            get {
                return this.costumerIDField;
            }
            set {
                this.costumerIDField = value;
                this.RaisePropertyChanged("costumerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int reservStatsID {
            get {
                return this.reservStatsIDField;
            }
            set {
                this.reservStatsIDField = value;
                this.RaisePropertyChanged("reservStatsID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string couponCode {
            get {
                return this.couponCodeField;
            }
            set {
                this.couponCodeField = value;
                this.RaisePropertyChanged("couponCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListCarsServiceSoapChannel : RentalCarWeb.ListCarsServiceReference.ListCarsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListCarsServiceSoapClient : System.ServiceModel.ClientBase<RentalCarWeb.ListCarsServiceReference.ListCarsServiceSoap>, RentalCarWeb.ListCarsServiceReference.ListCarsServiceSoap {
        
        public ListCarsServiceSoapClient() {
        }
        
        public ListCarsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListCarsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListCarsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListCarsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable readAllInDataTable() {
            return base.Channel.readAllInDataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> readAllInDataTableAsync() {
            return base.Channel.readAllInDataTableAsync();
        }
        
        public RentalCarWeb.ListCarsServiceReference.Car[] readAll() {
            return base.Channel.readAll();
        }
        
        public System.Threading.Tasks.Task<RentalCarWeb.ListCarsServiceReference.Car[]> readAllAsync() {
            return base.Channel.readAllAsync();
        }
        
        public RentalCarWeb.ListCarsServiceReference.Car[] searchCars(string plate, string model, string city, System.DateTime presentStartDate, System.DateTime presentEndDate) {
            return base.Channel.searchCars(plate, model, city, presentStartDate, presentEndDate);
        }
        
        public System.Threading.Tasks.Task<RentalCarWeb.ListCarsServiceReference.Car[]> searchCarsAsync(string plate, string model, string city, System.DateTime presentStartDate, System.DateTime presentEndDate) {
            return base.Channel.searchCarsAsync(plate, model, city, presentStartDate, presentEndDate);
        }
        
        public bool validateCarPlate(string carPlate) {
            return base.Channel.validateCarPlate(carPlate);
        }
        
        public System.Threading.Tasks.Task<bool> validateCarPlateAsync(string carPlate) {
            return base.Channel.validateCarPlateAsync(carPlate);
        }
        
        public bool validateCarModel(string carModel) {
            return base.Channel.validateCarModel(carModel);
        }
        
        public System.Threading.Tasks.Task<bool> validateCarModelAsync(string carModel) {
            return base.Channel.validateCarModelAsync(carModel);
        }
        
        public bool validateCity(string city) {
            return base.Channel.validateCity(city);
        }
        
        public System.Threading.Tasks.Task<bool> validateCityAsync(string city) {
            return base.Channel.validateCityAsync(city);
        }
        
        public bool validateDate(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.validateDate(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<bool> validateDateAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.validateDateAsync(startDate, endDate);
        }
        
        public bool validateRentPeriod(string plate, System.DateTime presentStartDate, System.DateTime presentEndDate, string condition, RentalCarWeb.ListCarsServiceReference.Reservation reservation) {
            return base.Channel.validateRentPeriod(plate, presentStartDate, presentEndDate, condition, reservation);
        }
        
        public System.Threading.Tasks.Task<bool> validateRentPeriodAsync(string plate, System.DateTime presentStartDate, System.DateTime presentEndDate, string condition, RentalCarWeb.ListCarsServiceReference.Reservation reservation) {
            return base.Channel.validateRentPeriodAsync(plate, presentStartDate, presentEndDate, condition, reservation);
        }
    }
}
